apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: influxdb
  name: influxdb
spec:
  ports:
  - name: 8000-8086
    port: 8000
    protocol: TCP
    targetPort: 8086
  selector:
    app: influxdb
  type: ClusterIP
status:
  loadBalancer: {}
